TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------

DBD = pmacAsynIPPort.dbd
INC += pmacAsynIPPort.h

LIBRARY = pmacAsynIPPort
pmacAsynIPPort_SRCS = pmacAsynIPPort.c 

include $(TOP)/configure/RULES
