# This file was automatically generated on Thu 15 Nov 2018 14:28:58 GMT from
# source: /home/hgv27681/R3.14.12.7/support/pmac/etc/makeIocs/lab.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(INSTALL)"

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(INSTALL)"

dbLoadDatabase "dbd/lab.dbd"
lab_registerRecordDeviceDriver(pdbbase)

# TODO - change the IP address below to match the required device
# Create SSH Port (PortName, IPAddress, Username, Password, Priority, DisableAutoConnect, noProcessEos)
drvAsynPowerPMACPortConfigure("BRICK1port", "172.23.247.1", "root", "deltatau", "0", "0", "0")

# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("Brick", "BRICK1port", 0, 8, 100, 1000)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("Brick", 8)

pmacDisableLimitsCheck("Brick", 1, 0)

pmacDisableLimitsCheck("Brick", 2, 0)

pmacDisableLimitsCheck("Brick", 3, 0)

pmacDisableLimitsCheck("Brick", 4, 0)

pmacDisableLimitsCheck("Brick", 5, 0)

pmacDisableLimitsCheck("Brick", 6, 0)

pmacDisableLimitsCheck("Brick", 7, 0)

pmacDisableLimitsCheck("Brick", 8, 0)

# Final ioc initialisation
# ------------------------
cd "$(INSTALL)"
dbLoadRecords 'db/lab_expanded.db'
iocInit
